[workspace]
resolver = "3"
members = ["kernel"]

[package]
name = "solaros"
version = "0.1.0"
edition = "2024"

[dependencies]

[build-dependencies]
solarcore = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }
bootloader = "0.11.17"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
